### ISSUE TITLE
Movement Keys

### ISSUE THREAD

**Issue by everlastingwonder** [fastrgv/RufasGate#1]
It's not a huge issue, but it would be nice to also be able to move with the WASD keys and look with the mouse. I'm used to using WASD in first-person games (anything where you look around with the mouse), and it's a bit difficult to use arrows and mouse, especially when spacebar is jump.

**Comment by fastrgv** [comment]
Good suggestion.  That's easy, and I will do it on all my active projects.  RufasGate is inactive because AdaGate is the newer replacement.  Please try it.  I'll enable those keys soon.
